#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/framework/app.php';

$app = new Kernel();
$app->boot();

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new App\Commands\ImportCharacters());
$status = $application->run();

exit($status);
